# Generated by Django 4.1.5 on 2023-03-15 19:49
import pandas as pd
from django.db import migrations

from api.models import Organization


def add_organizations(apps, schema_editor):
    df_organizations = pd.read_csv("api/data/Organizations.csv")
    for index, row in df_organizations.iterrows():
        new_organization = Organization(name=row['Name'])
        new_organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tags_data_migration'),
    ]

    operations = [
        migrations.RunPython(add_organizations),
    ]
