# Generated by Django 4.1.5 on 2023-05-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20230321_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='enabledDate',
            new_name='enabled_date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='evaluationMetric',
            new_name='evaluation_metric',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='maxDailySubmissions',
            new_name='max_daily_submissions',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='maxTeamSize',
            new_name='max_team_size',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='rewardQuantity',
            new_name='reward_quantity',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='rewardType',
            new_name='reward_type',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='totalCompetitors',
            new_name='total_competitors',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='totalSubmissions',
            new_name='total_submissions',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='totalTeams',
            new_name='total_teams',
        ),
    ]
